services:
  # for local development
  quasar:
    build:
      context: .
      dockerfile: Dockerfile
      target: 'develop-stage'
    ports:
      - '9001:9001'
    command: /bin/sh -c "npm install && npm run dev"
            